import { FieldDefinition } from "@/components/shared/form/RenderField";

export const employeeFields: FieldDefinition[] = [
  {
    label: "Emp Code",
    key: "empCode",
    type: "text",
    required: true,
  },
  {
    label: "First Name",
    key: "firstName",
    type: "text",
    required: true,
  },
  {
    label: "Last Name",
    key: "lastName",
    type: "text",
    required: true,
  },
  {
    label: "First Name (KH)",
    key: "firstNameKh",
    type: "text",
    required: false,
  },
  {
    label: "Last Name (KH)",
    key: "lastNameKh",
    type: "text",
    required: false,
  },
  {
    label: "Gender",
    key: "gender",
    type: "select",
    required: true,
    options: [
      { label: "Male", value: "MALE" },
      { label: "Female", value: "FEMALE" },
    ],
  },
  {
    label: "Date Of Birth",
    key: "dateOfBirth",
    type: "date",
    required: true,
  },
  {
    label: "Place Of Birth",
    key: "placeOfBirth",
    type: "text",
    required: false,
  },
  {
    label: "Nationality",
    key: "nationality",
    type: "text",
    required: false,
  },
  {
    label: "race",
    key: "race",
    type: "text",
    required: false,
  },
  {
    label: "Marital Status",
    key: "maritalStatus",
    type: "select",
    required: true,
  },
  {
    label: "Children Number",
    key: "childrenNumber",
    type: "number",
    required: false,
  },
  {
    label: "Phone",
    key: "phone",
    type: "phone",
    required: false,
  },
  {
    label: "Current Address",
    key: "currentAddress",
    type: "textarea",
    required: false,
  },
  {
    label: "Education",
    key: "education",
    type: "text",
    required: false,
  },
  {
    label: "Employee Type",
    key: "employeeType",
    type: "select",
    required: true,
    options: [
      { label: "Single", value: "SINGLE" },
      { label: "Married", value: "MARRIED" },
      { label: "Divorced", value: "DIVORCED" },
      { label: "Widowed", value: "WIDOWED" },
    ],
  },
  {
    label: "Work Status",
    key: "workStatus",
    type: "select",
    required: true,
    options: [
      { label: "Single", value: "SINGLE" },
      { label: "Married", value: "MARRIED" },
      { label: "Divorced", value: "DIVORCED" },
      { label: "Widowed", value: "WIDOWED" },
    ],
  },
  {
    label: "Employee Status",
    key: "employeeStatus",
    type: "select",
    required: true,
    options: [
      { label: "Probation", value: "PROBATION" },
      { label: "Contract", value: "CONTRACT" },
      { label: "Permanent", value: "PERMANENT" },
    ],
  },
  {
    label: "Start",
    key: "start",
    type: "date",
    required: true,
  },
  {
    label: "Position",
    key: "position",
    type: "text",
    required: true,
  },
  {
    label: "Start Sate",
    key: "startDate",
    type: "date",
    required: true,
  },
  {
    label: "End Date",
    key: "endDate",
    type: "date",
    required: false,
  },
  {
    label: "labor_book_no",
    key: "laborBookNo",
    type: "text",
    required: false,
  },
  {
    label: "id_card_no",
    key: "idCardNo",
    type: "text",
    required: false,
  },
  {
    label: "nssf_register_no",
    key: "nssfRegisterNo",
    type: "text",
    required: false,
  },
  {
    label: "working_shift",
    key: "workingShiftId",
    type: "select",
    required: true,
  },
];
